config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :events do
      collection do
        post :update_positions
      end
      resources :event_products do
        collection do
          post :update_positions
        end
      end
    end 
  end

  namespace :api do
    namespace :v1 do
      resources :events, only: [:index, :show], defaults: {format: :json} do
        get 'popular_events' => 'events#popular_events', on: :collection
      end
    end
  end
end

app/models/spree/event.rb
module Spree
  class Event < Base
    extend FriendlyId
    friendly_id :name, use: :slugged
    validates_presence_of :name, :slug

    acts_as_paranoid
    acts_as_list

    belongs_to :event_image
    has_many :event_products, -> { order(:position) }
    has_many :products, through: :event_products

    accepts_nested_attributes_for :event_image

    scope :sorted, -> { order("#{Spree::Event.table_name}.position ASC") }
    scope :visible, -> { where("#{Spree::Event.table_name}.start_time <= ?", Time.zone.now).where(hidden: false) }
    scope :not_deleted, -> { where("#{Spree::Event.quoted_table_name}.deleted_at IS NULL or #{Spree::Event.quoted_table_name}.deleted_at >= ?", Time.zone.now) }

    def available_products
      products.where('available_on is not null and available_on < ?', Time.current)
    end

    def product_ids
      products.pluck(:id)
    end

    def set_product_ids(product_ids)
      product_ids.uniq!
      origin_product_ids = event_products.pluck(:product_id)
      destroy_ids = origin_product_ids - product_ids
      Spree::EventProduct.transaction do
        event_products.where(product_id: destroy_ids).destroy_all if destroy_ids.present?
        new_product_ids = product_ids - origin_product_ids
        new_product_ids.each do |product_id|
          event_products.create(product_id: product_id)
        end
      end
    end

    attr_accessor :product_ids_string
    before_save do
      if product_ids_string
        ids = product_ids_string.split(",").map(&:to_i)
        set_product_ids(ids)
      end
    end

    def slug_candidates
      [
        :name,
        [:name, :id]
      ]
    end

    def should_generate_new_friendly_id
      name_changed? || super
    end

    def display_time_to_close
      diff = ((end_time || Time.zone.now) - Time.zone.now).seconds

      if diff <= 0
        I18n.t('event.time_to_close.now')
      elsif diff <= 24.hours
        I18n.t('event.time_to_close.in_hours', hours: (diff/1.hour).ceil)
      else
        I18n.t('event.time_to_close.in_days', days: (diff/1.day).ceil)
      end
    end

    def dynamic_attributes
      {
        display_time_to_close: display_time_to_close,
      }
    end

    def deleted?
      !!deleted_at
    end

    def index_products
      available_products.first(10)
    end

  end
end

app/models/spree/event_image.rb
module Spree
  class EventImage < Asset

    has_attached_file :attachment,
                      styles: {web_banner: '1200x516#', cover: '1200x516#', small: '384x165#'},
                      default_style: :cover,
                      convert_options: {all: '-strip -auto-orient -colorspace sRGB -interlace Plane -quality 80'}

    validate :no_attachment_errors
    validates_attachment :attachment,
      presence: true,
      content_type: { content_type: %w(image/jpeg image/jpg image/png image/gif) }

    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    before_save :find_dimensions

    #used by admin products autocomplete
    def mini_url
      attachment.url(:mini, false)
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

app/models/spree/event_product.rb
module Spree
  class EventProduct < Spree::Base
    belongs_to :event, class_name: 'Spree::Event'
    belongs_to :product, class_name: 'Spree::Product'
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :event_products, inverse_of: :product, dependent: :destroy
  has_many :events, through: :event_products
end

app/controllers/spree/admin/event_products_controller.rb
module Spree
  module Admin
    class EventProductsController < ResourceController
    end
  end
end

app/controllers/spree/admin/events_controller.rb
module Spree
  module Admin
    class EventsController < ResourceController

      before_action :load_data, except: :index

      def show
        redirect_to action: :edit
      end

      def edit
        @products = @event.products
      end

      def index
        session[:return_to] = request.url
        respond_with(@collection)
      end

      def update
        if (cover = params.maybe[:event].delete(:event_image).just)
          file = cover[:attachment]
          if file
            @event.event_image = Spree::EventImage.create!(attachment: file)
          end
        end

        super
      end

      def destroy
        @event = Spree::Event.friendly.find(params[:id])
        @event.destroy

        flash[:success] = Spree.t('notice_messages.event_deleted')

        respond_with(@event) do |format|
          format.html { redirect_to collection_url }
          format.js  { render_js_for_destroy }
        end
      end

      protected

      def find_resource
        Spree::Event.friendly.find(params[:id])
      end

      def location_after_save
        spree.edit_admin_event_url(@event)
      end

      def load_data
      end

      def collection
        return @collection if @collection.present?
        params[:q] ||= {}

        params[:q][:s] ||= "start_time_desc"
        show_hidden = params[:q].delete(:show_hidden).try(:to_i) || 1
        @collection = super
        # @search needs to be defined as this is passed to search_form_for
        @search = @collection.ransack(params[:q])
        @collection = @search.result.
          includes(event_includes).
          order(position: :asc).
          page(params[:page]).
          per(params[:per_page] || Spree::Config[:admin_products_per_page])

        @collection = @collection.where(hidden: false) if show_hidden == 0
        params[:q][:show_hidden] = show_hidden

        @collection
      end

      def event_includes
        [{:event_products => :product}]
      end

    end
  end
end

app/controllers/spree/api/base_controller_decorator.rb
Spree::Api::BaseController.class_eval do
  def find_event(id)
    event_scope.friendly.distinct(false).find(id.to_s)
  rescue ActiveRecord::RecordNotFound
    event_scope.find(id)
  end

  def event_scope
    if @current_user_roles.include?("admin")
      scope = Spree::Event.with_deleted.accessible_by(current_ability, :read).includes(*event_includes)

      unless params[:show_deleted]
        scope = scope.not_deleted
      end
    else
      scope = Spree::Event.visible.accessible_by(current_ability, :read).active.includes(*event_includes)
    end

    scope
  end

  def event_includes
    [ :event_products, :products ]
  end
end

app/controllers/spree/api/v1/events_controller.rb
module Spree
  module Api
    module V1
      class EventsController < Spree::Api::BaseController
        def index
          if params[:ids]
            @events = event_scope.where(id: params[:ids].split(",").flatten)
          else
            @events = event_scope.ransack(params[:q]).result
          end

          @events = @events.distinct.page(params[:page]).per(params[:per_page])
          expires_in 15.minutes, public: true
          headers['Surrogate-Control'] = "max-age=#{15.minutes}"
          respond_with(@events)
        end

        def show
          @event = find_event(params[:id])
          @products = @event.available_products.page(params[:page]).per(params[:per_page])
          expires_in 15.minutes, public: true
          headers['Surrogate-Control'] = "max-age=#{15.minutes}"
          headers['Surrogate-Key'] = "event_id=1"
          respond_with(@event, @products)
        end

        def popular_events
          @events = event_scope.sorted.visible.first(3);
        end
      end
    end
  end
end

app/views/spree/admin/events/edit.html.erb
<% content_for :page_actions do %>
    <% if can?(:create, Spree::Event) %>
        <%= button_link_to "New Event", new_object_url, { :class => 'btn-success', :icon => 'add', :id => 'admin_new_event' } %>
    <% end %>
<% end %>

<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @event } %>

<%= form_for [:admin, @event], :method => :put, :html => { :multipart => true } do |f| %>
    <fieldset>
      <div data-hook="admin_event_form_fields">

        <div data-hook="admin_event_form_name">
          <%= f.field_container :name, class: ['form-group'] do %>
              <%= f.label :name, raw(Spree.t(:name) + content_tag(:span, ' *', class: 'required')) %>
              <%= f.text_field :name, class: 'form-control title' %>
              <%= f.error_message_on :name %>
          <% end %>
        </div>

        <div data-hook="admin_event_form_description">
          <%= f.field_container :description, class: ['form-group'] do %>
              <%= f.label :description, Spree.t(:description)  %>
              <%= f.text_area :description, class: 'form-control' %>
              <%= f.error_message_on :description %>
          <% end %>
        </div>

        <div data-hook="admin_event_form_start_time">
          <%= f.field_container :start_time, class: ['form-group'] do %>
              <%= f.label :start_time, 'Start Time' %>
              <%= f.error_message_on :start_time %>
              <%= f.text_field :start_time, value: @event.start_time, class: 'datetimepicker form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_event_form_end_time">
          <%= f.field_container :end_time, class: ['form-group'] do %>
              <%= f.label :end_time, 'End Time' %>
              <%= f.error_message_on :end_time %>
              <%= f.text_field :end_time, value: @event.end_time, class: 'datetimepicker form-control' %>
          <% end %>
        </div>

        <div class="form-group event_hidden">
          <%= f.field_container :hidden, class: ['form-group'] do %>
              <%= f.label :hidden, 'Hidden' %>
              <%= f.error_message_on :hidden%>
              <%= f.check_box :hidden, value: @event.hidden, class: 'form-control' %>
          <% end %>
        </div>

        <div data-hook="admin_event_event_image">
          <%= f.field_container :event_image, class: ['form-group'] do %>
              <%= f.label :event_image, raw("Cover Image" + content_tag(:span, ' *', class: 'required')) %>
              <%= f.file_field :attachment, name: "event[event_image][attachment]" %>
              <%= f.error_message_on :event_image %>
              <% if @event.event_image %>
                  <%= link_to image_tag(
                      @event.event_image.attachment.url(:cover),
                      width: 100, height: 50),
                    @event.event_image.attachment.url(:cover)
                  %>
              <% else %>
                  <span>No Cover Image Yet</span>
              <% end %>
          <% end %>
        </div>

        <div class="form-group event_products">
          <%= label_tag "event_product_ids_string", "Products" %>
          <%= hidden_field_tag "event[product_ids_string]", @event.products.pluck(:id).join(","), :class => "product_picker" %>
        </div>

        <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
      </div>
    </fieldset>
  <% end %>

<div class="form-group" style="margin-top: 30px">
  <% if @event.event_products.any? %>
    <table class="table table-striped sortable" data-hook="products_table" data-sortable-link="<%= update_positions_admin_event_event_products_url(@event, @event.event_products) %>">
      <thead>
        <tr data-hook="products_header">
          <th></th>
          <th>Product Id</th>
        <th>
          <%= Spree.t(:thumbnail) %>
        </th>
        <th>
          Name
        </th>
        <th>
          Brand
        </th>
        <th>
          On Hand
        </th>
        <th class="actions"></th>
      </tr>
      </thead>

      <tbody>
      <% (@products || []).each do |product| %>
          <% css_class = product.available? ? '' : "gray-background" %>
          <tr id="<%= spree_dom_id(product.event_products.find_by(event_id: @event.id)) %>" data-hook="products_row" class="<%= css_class %>">
            <td class="move-handle text-center">
              <span class="icon icon-move handle"></span>
            </td>
            <td><%= product.id %></td>
            <td class="product">
              <%= link_to image_tag(product.maybe.images.first.attachment.url(:small).just), spree.edit_admin_product_url(product) %>
            </td>
            <td><%= product.name %></td>
            <td><%= product.property(:brand) %></td>
            <td><%= product.total_on_hand %></td>
            <td class="actions actions-2 text-right">
              <%= link_to_with_icon('edit', Spree.t(:edit), spree.edit_admin_product_url(product), class: 'btn btn-primary btn-sm', no_text: true, data: { action: 'edit' }) if can? :edit, product %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Product)) %>,
    </div>
<% end %>
</div>

app/views/spree/admin/events/index.html.erb
<% content_for :page_title do %>
    <%= plural_resource_name(Spree::Event) %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to "New Event", new_object_url, { :class => "btn-success", :icon => 'add', :id => 'admin_new_event' } %>
<% end if can?(:create, Spree::Event) %>

<% content_for :table_filter do %>
    <div data-hook="admin_products_sidebar">

      <%= search_form_for [:admin, @search] do |f| %>
          <%- locals = {:f => f} %>
          <div data-hook="admin_products_index_search" class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :name_cont, Spree.t(:name) %>
                <%= f.text_field :name_cont, :value => params[:q][:name_cont], :size => 15, class: "form-control js-quick-search-target" %>
              </div>
            </div>

            <div class="date-range-filter col-md-12">
              <div class="form-group">
                <%= label_tag :q_created_at_gt, Spree.t(:created_time_range) %>
                <div class="row no-padding-bottom">
                  <div class="col-md-6">
                    <div class="input-group">
                      <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from form-control', :value => params[:q][:created_at_gt], :placeholder => Spree.t(:start) %>
                      <span class="input-group-addon"><i class="icon icon-calendar"></i> </span>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="input-group">
                      <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to form-control', :value => params[:q][:created_at_lt], :placeholder => Spree.t(:stop) %>
                      <span class="input-group-addon"><i class="icon icon-calendar"></i></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>


            <div class="col-md-2">
              <div class="field checkbox">
                <label>
                  <%= f.check_box :show_hidden, {:checked => params[:q][:show_hidden] != '0'}, '1', '0' %>
                  <%= Spree.t(:show_hidden) %>
                </label>
              </div>
            </div>
          </div>
          <div data-hook="admin_products_index_search_buttons" class="form-actions">
            <%= button Spree.t(:search), 'search' %>
          </div>
      <% end %>

    </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>
<% if @collection.any? %>
    <table class="table sortable" id="listing_events"  data-hook="events_table" data-sortable-link="<%= update_positions_admin_events_url(@collection, format: :js) %>">
      <thead>
      <tr data-hook="admin_events_index_headers">
        <th></th>
        <th>Id</th>
        <th>Image</th>
        <th><%= sort_link @search, :name, Spree.t(:name), { default_order: "desc" }, {title: 'admin_events_listing_name_title'} %></th>
        <th>
          <%= sort_link @search, :start_time, 'Start Time', {}, {title: 'admin_events_start_time'} %>
        </th>
        <th>
          <%= sort_link @search, :end_time, 'End Time', {}, {title: 'admin_events_end_time'} %>
        </th>
        <th>
          <%= sort_link @search, :created_at, 'Created At', {default_order: 'desc'}, {title: 'admin_events_created_at'} %>
        </th>
        <th>
          <%= sort_link @search, :updated_at, 'Updated At', {default_order: 'desc'}, {title: 'admin_events_updated_at'} %>
        </th>
        <th>Hidden</th>
        <th>Item Count</th>
        <th data-hook="admin_events_index_header_actions" class="actions"></th>
      </tr>
      </thead>
      <tbody>
      <% @collection.each do |event| %>
          <tr id="<%= spree_dom_id event %>" data-hook="admin_events_index_rows" class="<%= cycle('odd', 'even') %>">
            <td class="move-handle text-center">
              <span class="icon icon-move handle"></span>
            </td>
            <td><%= event.id %></td>
            <td class="image">
              <% if event.event_image.present? %>
                <%= image_tag event.maybe.event_image.attachment.url(:cover).just, height: 50, width: 100 %>
              <% end %>
            </td>
            <td><%= link_to event.try(:name), edit_admin_event_path(event.friendly_id) %></td>
            <td><%= event.start_time %></td>
            <td><%= event.end_time %></td>
            <td><%= event.created_at %></td>
            <td><%= event.updated_at %></td>
            <td><%= event.hidden %></td>
            <td><%= event.products.count %></td>
            <td class="actions actions-1 text-right" data-hook="admin_events_index_row_actions">
              <%= link_to_edit event, no_text: true, class: 'edit' if can?(:edit, event) %>
              <%= link_to_delete event, no_text: true if can?(:delete, event) && !event.deleted? %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Event)) %>,
      <%= link_to Spree.t(:add_one), new_object_url %>!
    </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

app/views/spree/admin/events/new.html.erb
<%= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @event } %>

<% content_for :page_title do %>
    New Event
<% end %>

<%= form_for [:admin, @event], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_event">
    <%= f.field_container :name, :class => ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
      <%= f.text_field :name, :class => 'form-control title' %>
      <%= f.error_message_on :name %>
    <% end %>

    <div data-hook="admin_event_form_start_time">
      <%= f.field_container :start_time, class: ['form-group'] do %>
          <%= f.label :start_time, 'Start Time' %> <span class="required">*</span>
          <%= f.error_message_on :start_time %>
          <%= f.text_field :start_time, value: datepicker_field_value(@event.start_time), class: 'datepicker form-control' %>
      <% end %>
    </div>

    <div data-hook="admin_event_form_end_time">
      <%= f.field_container :end_time, class: ['form-group'] do %>
          <%= f.label :end_time, 'End Time' %> <span class="required">*</span>
          <%= f.error_message_on :end_time %>
          <%= f.text_field :end_time, value: datepicker_field_value(@event.end_time), class: 'datepicker form-control' %>
      <% end %>
    </div>

    <%= hidden_field_tag "event[hidden]", true %>

    <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/shared/_events_sidebar_menu.html.erb
<% if can? :admin, Spree::Event %>
  <ul class="nav nav-sidebar">
    <%= tab Spree::Event, url: spree.admin_events_url, icon: 'file', label: plural_resource_name(Spree::Event) %>
  </ul>
<% end %>

app/views/spree/admin/shared/sub_menu/_event.html.erb
<ul id="sidebar-event" class="collapse nav nav-pills nav-stacked" data-hook="admin_event_sub_tabs">
  <%= tab :events %>
</ul>